// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {neocronapi} from '../models';
import {config} from '../models';
import {addon} from '../models';
import {updater} from '../models';
import {proton} from '../models';
import {launcher} from '../models';
import {main} from '../models';

export function APIGetToken():Promise<string>;

export function APIIsSessionValid():Promise<boolean>;

export function APILogin(arg1:string,arg2:string):Promise<neocronapi.SessionDetails>;

export function APILogout():Promise<void>;

export function AddServer(arg1:config.ServerEndpoint):Promise<void>;

export function CancelProtonDownload():Promise<void>;

export function CancelUpdate():Promise<void>;

export function CheckAddonUpdates():Promise<Array<addon.AddonUpdate>>;

export function CheckForUpdate():Promise<updater.UpdateCheckResult>;

export function DisableAddon(arg1:string):Promise<void>;

export function DownloadProton(arg1:string):Promise<void>;

export function EnableAddon(arg1:string):Promise<void>;

export function GetApplications():Promise<Array<neocronapi.Application>>;

export function GetAvailableProtonVersions():Promise<Array<proton.GHRelease>>;

export function GetConfig():Promise<config.Config>;

export function GetGameEndpoints(arg1:string):Promise<Array<neocronapi.Endpoint>>;

export function GetGameStatus():Promise<launcher.GameStatus>;

export function GetInstalledAddons():Promise<Array<addon.InstalledAddon>>;

export function GetLauncherVersion():Promise<string>;

export function GetLocalVersion():Promise<string>;

export function GetMissingExpected():Promise<Record<string, Array<string>>>;

export function GetPlatformInfo():Promise<main.PlatformInfo>;

export function GetPrefixStatus():Promise<proton.PrefixStatus>;

export function GetProtonBuilds():Promise<Array<proton.Build>>;

export function GetServerVersion():Promise<string>;

export function GetUpdateProgress():Promise<updater.Progress>;

export function ImportEndpointsAsServers(arg1:string):Promise<void>;

export function InstallAddon(arg1:string):Promise<void>;

export function IsGameInstalled():Promise<boolean>;

export function KillGame():Promise<void>;

export function LaunchGame():Promise<void>;

export function RemoveProtonBuild(arg1:string):Promise<void>;

export function RemoveServer(arg1:number):Promise<void>;

export function ReorderAddons(arg1:Array<string>):Promise<void>;

export function RunSysConfig():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetActiveServer(arg1:number):Promise<void>;

export function SetAddonPriority(arg1:string,arg2:number):Promise<void>;

export function SetProtonBuild(arg1:string,arg2:string):Promise<void>;

export function SetupPrefix():Promise<void>;

export function StartInstall():Promise<void>;

export function StartUpdate():Promise<void>;

export function UninstallAddon(arg1:string):Promise<void>;

export function UpdateAddon(arg1:string):Promise<void>;
