// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIGetToken() {
  return window['go']['main']['App']['APIGetToken']();
}

export function APIIsSessionValid() {
  return window['go']['main']['App']['APIIsSessionValid']();
}

export function APILogin(arg1, arg2) {
  return window['go']['main']['App']['APILogin'](arg1, arg2);
}

export function APILogout() {
  return window['go']['main']['App']['APILogout']();
}

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function CancelProtonDownload() {
  return window['go']['main']['App']['CancelProtonDownload']();
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckAddonUpdates() {
  return window['go']['main']['App']['CheckAddonUpdates']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DisableAddon(arg1) {
  return window['go']['main']['App']['DisableAddon'](arg1);
}

export function DownloadProton(arg1) {
  return window['go']['main']['App']['DownloadProton'](arg1);
}

export function EnableAddon(arg1) {
  return window['go']['main']['App']['EnableAddon'](arg1);
}

export function GetApplications() {
  return window['go']['main']['App']['GetApplications']();
}

export function GetAvailableProtonVersions() {
  return window['go']['main']['App']['GetAvailableProtonVersions']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGameEndpoints(arg1) {
  return window['go']['main']['App']['GetGameEndpoints'](arg1);
}

export function GetGameStatus() {
  return window['go']['main']['App']['GetGameStatus']();
}

export function GetInstalledAddons() {
  return window['go']['main']['App']['GetInstalledAddons']();
}

export function GetLauncherVersion() {
  return window['go']['main']['App']['GetLauncherVersion']();
}

export function GetLocalVersion() {
  return window['go']['main']['App']['GetLocalVersion']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetPrefixStatus() {
  return window['go']['main']['App']['GetPrefixStatus']();
}

export function GetProtonBuilds() {
  return window['go']['main']['App']['GetProtonBuilds']();
}

export function GetServerVersion() {
  return window['go']['main']['App']['GetServerVersion']();
}

export function GetUpdateProgress() {
  return window['go']['main']['App']['GetUpdateProgress']();
}

export function ImportEndpointsAsServers(arg1) {
  return window['go']['main']['App']['ImportEndpointsAsServers'](arg1);
}

export function InstallAddon(arg1) {
  return window['go']['main']['App']['InstallAddon'](arg1);
}

export function IsGameInstalled() {
  return window['go']['main']['App']['IsGameInstalled']();
}

export function KillGame() {
  return window['go']['main']['App']['KillGame']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function RemoveProtonBuild(arg1) {
  return window['go']['main']['App']['RemoveProtonBuild'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function RunSysConfig() {
  return window['go']['main']['App']['RunSysConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SetProtonBuild(arg1, arg2) {
  return window['go']['main']['App']['SetProtonBuild'](arg1, arg2);
}

export function SetupPrefix() {
  return window['go']['main']['App']['SetupPrefix']();
}

export function StartInstall() {
  return window['go']['main']['App']['StartInstall']();
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}

export function ReorderAddons(arg1) {
  return window['go']['main']['App']['ReorderAddons'](arg1);
}

export function SetAddonPriority(arg1, arg2) {
  return window['go']['main']['App']['SetAddonPriority'](arg1, arg2);
}

export function GetMissingExpected() {
  return window['go']['main']['App']['GetMissingExpected']();
}

export function UninstallAddon(arg1) {
  return window['go']['main']['App']['UninstallAddon'](arg1);
}

export function UpdateAddon(arg1) {
  return window['go']['main']['App']['UpdateAddon'](arg1);
}
